'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class listaproduto
    Public Property cliente As String
    Public Property pedido As Boolean
    Public Property data As Integer
    Public Property preco As Integer
    Public Property id_produto As Integer
    Public Property nome_produto As Integer
    Public Property quantidade As Integer
    Public Property valor As Integer

End Class
